### PR TITLE
try to handle dates with no end per rfc

### PR DESCRIPTION
**Pull request by rndmh3ro**

### CODE REVIEW

**Review by mziech — APPROVED** [review]
Cool, thanks! (assuming you properly tested it)

**Comment by rndmh3ro** [comment]
I tested it on my instance where some events broke the app, so yeah. :)

**Comment by mziech** [comment]
I reworked the code a bit since it broke some events created with the calendar app on my side. Maybe you want to check the most recent release.

**Comment by rndmh3ro** [comment]
Sorry for breaking your app!

Your fixes still work for me.

**Comment by mziech** [comment]
No worries, glad to hear! You contribution is still highly appreciated ...

**Pull request merged**
